export const USER_LOADING_FIRST_DATA = "USER_LOADING_FIRST_DATA";

export const GET_USER_DATA = "GET_USER_DATA";

export const ERROR_USER_DATA_FAILED = "ERROR_USER_DATA_FAILED";

export const USER_NAME_GET_LOCALSTORAGE_GET = "USER_NAME_GET_LOCALSTORAGE_GET";
export const USER_NAME_GET_LOCALSTORAGE_LOADING = "USER_NAME_GET_LOCALSTORAGE_LOADING";
export const USER_NAME_GET_LOCALSTORAGE_ERROR= "USER_NAME_GET_LOCALSTORAGE_ERROR";
